R4C/urls.py
from django.contrib import admin
from django.urls import include, path

from robots.views import Home

app_name = 'r4c'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('robots/', include('robots.urls')),
    path('customers/', include('customers.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

robots/urls.py
from django.urls import path

from api.views import download_summary
from robots import views

app_name = 'robots'

urlpatterns = [
    path('', views.RobotRead.as_view(), name='read'),
    path('create/', views.RobotCreate.as_view(), name='create'),
    path('<int:pk>/', views.RobotEdit.as_view(), name='edit'),
    path('<int:pk>/delete/', views.RobotDelete.as_view(), name='delete'),
    path('home/', views.Home.as_view(), name='home'),
    path('download_summary/', download_summary, name='summary'),
]

robots/models.py
from django.db import models


class Robot(models.Model):
    serial = models.CharField(max_length=5, blank=False, null=False)
    model = models.CharField(max_length=2, blank=False, null=False)
    version = models.CharField(max_length=2, blank=False, null=False)
    created = models.DateTimeField(blank=False, null=False)

robots/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from api.serializers import RobotPostSerializer
from robots.models import Robot


class Home(TemplateView):
    template_name = 'index.html'


class RobotRead(generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'robots/read.html'

    def get(self, request):
        robots = Robot.objects.all()
        return Response({'robots': robots})


class RobotCreate(generics.CreateAPIView):
    serializer_class = RobotPostSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'robots/create.html'

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('robots:read')
        else:
            context = {'serializer': serializer}
            return Response(context, template_name=self.template_name)


class RobotEdit(generics.UpdateAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'robots/edit.html'

    def get(self, request, pk):
        robot = get_object_or_404(Robot, pk=pk)
        serializer = RobotPostSerializer(robot)
        return Response({'serializer': serializer, 'robot': robot})

    def post(self, request, pk, *args, **kwargs):
        robot = get_object_or_404(Robot, pk=pk)
        serializer = RobotPostSerializer(robot, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('robots:read')
        else:
            context = {'serializer': serializer}
            return Response(context, template_name='robots/create.html')


class RobotDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, pk):
        robot = get_object_or_404(Robot, pk=pk)
        context = {'pk': pk}
        robot.delete()
        return Response(context, template_name='robots/delete.html')

templates/robots/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load rest_framework %}

{% block content %}

<h1 class="pb-2 mb-0">Создание робота</h1>

  {% for message in messages %}
  <div class="alert alert-secondary" role="alert">
    {{message}}
  </div>
  {% endfor %}

    <form role="form" method="POST" autocomplete="off">                   
        <div class='row mt-2'>
            {% csrf_token %}
            {% render_form serializer %}
        </div>
        <button class="btn btn-success btn-md float-end mt-2 mb-0 mx-2" type="submit">Сохранить</button>
    </form>


{% endblock %}

templates/robots/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="pb-2 mb-0">Удаление робота</h1>

<div class="card-header">
    Робот под номером {{ pk }} удалён!
</div>

{% endblock %}

templates/robots/edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}
<h1 class="pb-2 mb-0">Редактирование робота</h1>

<div class="card-body">
<form action="{% url 'robots:edit' pk=robot.pk %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    {% bootstrap_button button_type="submit" content="Отправить" %} 
</form>
</div>

{% endblock %}

templates/robots/read.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}
<h1 class="pb-2 mb-0">Список роботов</h1>


  <a href="{% url 'robots:summary' %}" >СКАЧАТЬ СПИСОК РОБОТОВ</a>
  <hr>

  <form action="{% url 'robots:create' %}" method="post" class="col-3">
    {% bootstrap_button button_type="submit" content="Создать робота" %}
  </form>
  
  <hr>

  {% for robot in robots %}
  <div class="row">
    <div class="col-8"> 
        <div>
          <b>{{ robot.id }}</b> {{ robot.serial}} | создан {{ robot.created|date:"Y-n-d H:i:s"}} 
        </div>
    </div>
    <div class="col-4"> 
        <div>
          <a href="{% url 'robots:edit' robot.id %}" >Изменить</a>
          <a href="{% url 'robots:delete' robot.id %}" >Удалить</a>
        </div>
    </div>
    {% if not forloop.last %}
    <hr class="mt-3">
    {% endif %}
  </div>
  {% endfor %}
{% endblock %}