R4C/urls.py
from django.contrib import admin
from django.urls import include, path

from robots.views import Home

app_name = 'r4c'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('robots/', include('robots.urls')),
    path('customers/', include('customers.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

customers/urls.py
from django.urls import path

from customers import views

app_name = 'customers'

urlpatterns = [
    path('', views.CustomerRead.as_view(), name='read'),
    path('create/', views.CustomerCreate.as_view(), name='create'),
    path('<int:pk>/', views.CustomerEdit.as_view(), name='edit'),
    path('<int:pk>/delete/', views.CustomerDelete.as_view(), name='delete'),
]

customers/models.py
from django.db import models


class Customer(models.Model):
    email = models.CharField(max_length=255,blank=False, null=False)

    def __str__(self):
        return self.email

customers/views.py
from django.shortcuts import get_object_or_404, redirect
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from api.serializers import CustomerSerializer
from customers.models import Customer


class CustomerRead(generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'customers/read.html'

    def get(self, request):
        customers = Customer.objects.all()
        return Response({'customers': customers})


class CustomerCreate(generics.CreateAPIView):
    serializer_class = CustomerSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'customers/create.html'

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('customers:read')
        else:
            context = {'serializer': serializer}
            return Response(context, template_name=self.template_name)


class CustomerEdit(generics.UpdateAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'customers/edit.html'

    def get(self, request, pk):
        customer = get_object_or_404(Customer, pk=pk)
        serializer = CustomerSerializer(customer)
        return Response({'serializer': serializer, 'customer': customer})

    def post(self, request, pk, *args, **kwargs):
        customer = get_object_or_404(Customer, pk=pk)
        serializer = CustomerSerializer(customer, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('customers:read')
        else:
            context = {'serializer': serializer}
            return Response(context, template_name='customers/create.html')


class CustomerDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, pk):
        customer = get_object_or_404(Customer, pk=pk)
        context = {'pk': pk}
        customer.delete()
        return Response(context, template_name='customers/delete.html')

templates/customers/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load rest_framework %}

{% block content %}
<h1 class="pb-2 mb-0">Создание покупателя</h1>

  {% for message in messages %}
  <div class="alert alert-secondary" role="alert">
    {{message}}
  </div>
  {% endfor %}

    <form role="form" method="POST" autocomplete="off">                   
        <div class='row mt-2'>
            {% csrf_token %}
            {% render_form serializer %}
        </div>
        <button class="btn btn-success btn-md float-end mt-2 mb-0 mx-2" type="submit">Сохранить</button>
    </form>


{% endblock %}

templates/customers/customer_create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load rest_framework %}

{% block content %}


  {% for message in messages %}
  <div class="alert alert-secondary" role="alert">
    {{message}}
  </div>
  {% endfor %}

    <form role="form" method="POST" autocomplete="off">                   
        <div class='row mt-2'>
            {% csrf_token %}
            {% render_form serializer %}
        </div>
        <button class="btn btn-success btn-md float-end mt-2 mb-0 mx-2" type="submit">Save</button>
    </form>


{% endblock %}

templates/customers/customer_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}

<div class="card-header">
    Покупатель под номером {{ pk }} удалён!
</div>

{% endblock %}

templates/customers/customer_edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}

<div class="card-body">
<form action="{% url 'customers:edit' pk=customer.pk %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    {% bootstrap_button button_type="submit" content="Отправить" %} 
</form>
</div>

{% endblock %}

templates/customers/customer_read.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}

  <form action="{% url 'customers:create' %}" method="post" class="col-3">
    {% bootstrap_button button_type="submit" content="Создать покупателя" %}
  </form>

  <hr>
  {% for customer in customers %}
  <div class="row">
    <div class="col-8"> 
        <div>
          <b>{{ customer.id }}</b>   {{ customer.email}} 
        </div>
    </div>
    <div class="col-4"> 
        <div>
          <a href="{% url 'customers:edit' customer.id %}" >Изменить</a>
          <a href="{% url 'customers:delete' customer.id %}" >Удалить</a>
        </div>
    </div>
    {% if not forloop.last %}
    <hr class="mt-3">
    {% endif %}
  </div>
  {% endfor %}
{% endblock %}

templates/customers/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="pb-2 mb-0">Удаление покупателя</h1>

<div class="card-header">
    Покупатель под номером {{ pk }} удалён!
</div>

{% endblock %}

templates/customers/edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}
<h1 class="pb-2 mb-0">Редактирование покупателя</h1>

<div class="card-body">
<form action="{% url 'customers:edit' pk=customer.pk %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    {% bootstrap_button button_type="submit" content="Отправить" %} 
</form>
</div>

{% endblock %}

templates/customers/read.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}
<h1 class="pb-2 mb-0">Список покупателей</h1>

  <form action="{% url 'customers:create' %}" method="post" class="col-3">
    {% bootstrap_button button_type="submit" content="Создать покупателя" %}
  </form>

  <hr>
  {% for customer in customers %}
  <div class="row">
    <div class="col-8"> 
        <div>
          <b>{{ customer.id }}</b>   {{ customer.email}} 
        </div>
    </div>
    <div class="col-4"> 
        <div>
          <a href="{% url 'customers:edit' customer.id %}" >Изменить</a>
          <a href="{% url 'customers:delete' customer.id %}" >Удалить</a>
        </div>
    </div>
    {% if not forloop.last %}
    <hr class="mt-3">
    {% endif %}
  </div>
  {% endfor %}
{% endblock %}