R4C/urls.py
from django.contrib import admin
from django.urls import include, path

from robots.views import Home

app_name = 'r4c'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('robots/', include('robots.urls')),
    path('customers/', include('customers.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('', views.OrderRead.as_view(), name='read'),
    path('create/', views.OrderCreate.as_view(), name='create'),
    path('<int:pk>/', views.OrderEdit.as_view(), name='edit'),
    path('<int:pk>/delete/', views.OrderDelete.as_view(), name='delete'),
]

orders/models.py
from django.db import models

from customers.models import Customer


class Order(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    robot_serial = models.CharField(max_length=5,blank=False, null=False)

orders/views.py
from django.shortcuts import get_object_or_404, redirect
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from api.serializers import OrderSerializer
from orders.models import Order


class OrderRead(generics.ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'orders/read.html'

    def get(self, request):
        orders = Order.objects.all()
        return Response({'orders': orders})


class OrderCreate(generics.CreateAPIView):
    serializer_class = OrderSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'orders/create.html'

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('orders:read')
        else:
            context = {'serializer': serializer}
            return Response(context, template_name=self.template_name)


class OrderEdit(generics.UpdateAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'orders/edit.html'

    def get(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        serializer = OrderSerializer(order)
        return Response({'serializer': serializer, 'order': order})

    def post(self, request, pk, *args, **kwargs):
        order = get_object_or_404(Order, pk=pk)
        serializer = OrderSerializer(order, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('orders:read')
        else:
            context = {'serializer': serializer}
            return Response(context, template_name='orders/create.html')


class OrderDelete(APIView):
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request, pk):
        order = get_object_or_404(Order, pk=pk)
        context = {'pk': pk}
        order.delete()
        return Response(context, template_name='orders/delete.html')

templates/orders/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load rest_framework %}

{% block content %}
<h1 class="pb-2 mb-0">Создание заказа</h1>


  {% for message in messages %}
  <div class="alert alert-secondary" role="alert">
    {{message}}
  </div>
  {% endfor %}

    <form role="form" method="POST" autocomplete="off">                   
        <div class='row mt-2'>
            {% csrf_token %}
            {% render_form serializer %}
        </div>
        <button class="btn btn-success btn-md float-end mt-2 mb-0 mx-2" type="submit">Сохранить</button>
    </form>


{% endblock %}

templates/orders/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="pb-2 mb-0">Удаление заказа</h1>

<div class="card-header">
    Заказ под номером {{ pk }} удалён!
</div>

{% endblock %}

templates/orders/edit.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}
<h1 class="pb-2 mb-0">Редактирование заказа</h1>

<div class="card-body">
<form action="{% url 'orders:edit' pk=order.pk %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    {% bootstrap_button button_type="submit" content="Отправить" %} 
</form>
</div>

{% endblock %}

templates/orders/read.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load rest_framework %}
{% block content %}
<h1 class="pb-2 mb-0">Список заказов</h1>
  <form action="{% url 'orders:create' %}" method="post" class="col-3">
    {% bootstrap_button button_type="submit" content="Создать заказ" %}
  </form>

  <hr>
  {% for order in orders %}
  <div class="row">
    <div class="col-8"> 
        <div>
          <b>{{ order.id }}</b>  Покупатель с почтой <b>{{ order.customer.email}}</b>  хочет получить робота <b> {{ order.robot_serial}} </b>
        </div>
    </div>
    <div class="col-4"> 
        <div>
          <a href="{% url 'orders:edit' order.id %}" >Изменить</a>
          <a href="{% url 'orders:delete' order.id %}" >Удалить</a>
        </div>
    </div>
    {% if not forloop.last %}
    <hr class="mt-3">
    {% endif %}
  </div>
  {% endfor %}
{% endblock %}